Fullscreen plugin
SpringRoll/SpringRoll pull request #287
Opened 2020-12-04 17:10 UTC by BaileyBrightman

Tasks:
- [x] Documentation
- [x] Unit Tests
- [x] Typescript Typings
- [x] `npm run build:full`

2020-12-08 15:46 UTC, 902seanryan commented
One quick note:
Just add `.DS_Store` to the `.gitignore` file

I thought I'd done that already but I guess I missed it in this repo. Not a comment on your PR just something we should add.

2020-12-08 15:47 UTC, 902seanryan requested changes

2020-12-08 15:47 UTC, 902seanryan commented on src/Application.js
> +const fullscreen = 'fullscreen';
I would update this to be `fullScreen` not `fullscreen` just a little more readable. Make sure it update it everywhere.

2020-12-08 17:04 UTC, 902seanryan approved these changes

2020-12-14 14:41 UTC, aberkie approved these changes

2021-01-04 17:35 UTC, 902seanryan requested changes
Looks like some of the IndexDB stuff made it into this PR, can you remove them and we'll include them in a separate PR once its closer to completion.

2021-01-07 15:40 UTC, 902seanryan submitted a review, later dismissed

2021-01-08 15:08 UTC, 902seanryan commented
So this looks good to me, we just have to hold off merging until we sort out the node version support stuff.

2021-01-14 18:30 UTC, 902seanryan submitted a review, later dismissed

2021-01-22 13:58 UTC, aberkie approved these changes

2021-01-22 14:44 UTC, erinjoost approved these changes

2021-02-02 20:48 UTC, deycorinne approved these changes
looks good to me-- my one note is that the actual .DS_Store file is still in this PR even though you added it to he .gitignore. A quick `git rm .DS_Store` should fix that

2021-02-02 20:59 UTC, deycorinne approved these changes

2021-02-03 15:47 UTC, 902seanryan commented
@BaileyBrightman looks like there's a couple conflicts showing up. If you re-merge develop and then re-build, you should be good to go

2021-02-05 17:13 UTC, 902seanryan approved these changes

2021-02-05 17:29 UTC, deycorinne approved these changes

2021-02-10 20:32 UTC, aberkie approved these changes

2021-02-11 01:03 UTC, merged