Release/2.4.1
SpringRoll/SpringRoll pull request #306
Opened 2021-06-15 17:27 UTC by 902seanryan

This is mostly dependabot updates but also included the fullscreen typing update.

2021-06-16 15:46 UTC, deycorinne approved these changes

2021-06-16 15:49 UTC, BaileyBrightman approved these changes

2021-07-06 18:42 UTC, deycorinne requested changes

2021-07-06 18:42 UTC, deycorinne commented on CHANGELOG.md
> +- Bump browserslist from 4.14.0 to 4.16.6
Don't forget to add the latest dependabot change here as well!

2021-07-06 18:42 UTC, deycorinne commented on CHANGELOG.md
> +## [2.4.1] - 2021-05-16
oh, and to update this date!

2021-07-07 14:58 UTC, deycorinne approved these changes

2021-07-13 12:13 UTC, BaileyBrightman submitted a review, later dismissed

2021-07-19 13:31 UTC, aberkie approved these changes

2021-07-19 14:30 UTC, deycorinne approved these changes

2021-07-19 15:11 UTC, merged