Updated readme playOptions docs
SpringRoll/SpringRoll pull request #336
Opened 2022-07-06 18:27 UTC by lukemelong

2022-07-06 19:21 UTC, 902seanryan requested changes
two small nitpicks

2022-07-06 19:21 UTC, 902seanryan commented on src/README.md
>  Lastly, there are two other states available, one that has already been mentioned:
this line should be included in the Ready and Pause states section, probably want to tailor the language a bit (or just move the playOptions above)

2022-07-06 19:21 UTC, 902seanryan commented on src/README.md
>  myApp.state.playOptions.subscribe(playOptions => {
I'd probably add the `var myApp = newApplication()` just for completeness sake

2022-07-13 16:06 UTC, 902seanryan approved these changes

2022-07-13 16:08 UTC, 902seanryan approved these changes

2022-07-13 16:59 UTC, deycorinne approved these changes

2022-07-14 15:12 UTC, merged